name: 'Release'

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_REPO_TOKEN }}

      - name: 'Get yarn cache folder'
        id: yarn-cache
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: 'Handle yarn cache'
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
